[book]
authors = ["Mateusz Soltysik",]
language = "en"
multilingual = false
src = "src"

[output.html]
theme = "my-theme"
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://msoltysik.github.io/mbp-setup/"
