[book]
title = "Macbook Pro Setup"
authors = ["Mateusz Soltysik",]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "docs"

[output.html]
preferred-dark-theme = "ayu"
git-repository-url = "https://msoltysik.github.io/mbp-setup/"
